name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.5.0

    - name: Compile TS
      run: npm install && npm run build

  lint:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.5.0

    - name: Lint code
      run: npm install && npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [ lint ]
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.5.0

    - name: Compile TS and publish
      run: npm install && npm run build

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}